
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "tanhungho10",
  "password": "123456",
  "email": "hung10@gmail.com", 
  "fullName": "Hùng Hồ",
  "phone": "0987654321",
  "role": "user"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "tanhungho2",
  "password": "123456"
}

###
POST http://localhost:5000/api/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc

{
  "title": "Test 2",
  "description": "Two imprisoned men bond over a debt due to familial disputes after having been released from prison.",
  "duration": 142,
  "genre": ["Drama", "Crime"],
  "releaseDate": "1994-10-14",
  "director": "Frank Darabont",
  "cast": ["Frank Darabont", "Christopher Nolan", "Anurag Kashyap"],
  "poster": "https://www.imdb.com/title/tt0111161/mediaviewer/rm2488754688/",
  "trailer": "https://www.youtube.com/watch?v=6hB3S9bIaco",
  "rating": 9.3,
  "ageRate": 18,
  "country": "USA",
  "caption": "English",
  "status": "nowShowing"
}

###
PUT http://localhost:5000/api/movies/67b4851ff867fb27085bcbaf
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc

{
  "title": "Test Update Movie 1234",
  "description": "Two imprisoned men bond over a debt due to familial disputes after having been released from prison.",
  "duration": 142,
  "genre": ["Drama", "Crime"],
  "releaseDate": "1994-10-14",
  "director": "Frank Darabont",
  "cast": ["Frank Darabont", "Christopher Nolan", "Anurag Kashyap"],
  "poster": "https://www.imdb.com/title/tt0111161/mediaviewer/rm2488754688/",
  "trailer": "https://www.youtube.com/watch?v=6hB3S9bIaco",
  "rating": 9.3,
  "ageRate": 18,
  "country": "USA",
  "caption": "English",
  "status": "nowShowing"
}

###
DELETE  http://localhost:5000/api/movies/67b4cfeef89ea6a05e9ed154
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc

###
// Tạo room
POST http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc

{
  "name": "Room 3",
  "cinemaId": "67b75651ba9c7545a6904cea",
  "seats": [
    {
      "seatNumber": 1,
      "isBooked": false
    },
    {
      "seatNumber": 2,
      "isBooked": false
    },
    {
      "seatNumber": 2,
      "isBooked": false
    }
  ]
}
###
// Xóa Room
DELETE http://localhost:5000/api/rooms/67b75667ba9c7545a6904cee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc
###
//Tạo Cinema
POST http://localhost:5000/api/cinemas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc

{
  "name": "Cinema 6",
  "location": "Hồ Chí Minh",
  "phone": "0987654321",
  "rooms": ["67b756f1ba9c7545a6904d14","67b756aeba9c7545a6904cff"]
}

###
//Update Cinema

PUT http://localhost:5000/api/cinemas/67b74e8c74613370fa3dff12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc
 
{
  "name": "Cinema 3 test",
  "location": "Hồ Chí Minh",
  "phone": "0987654321",
  "rooms": ["67b741f3ada8613e2bdf4a65"]
}
###
// Xóa Cinema
DELETE http://localhost:5000/api/cinemas/67b748b7acc66114daa11dce
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2N2I0YzBjNmRiOThlYzg3ZGMyZGZjZDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk4OTkwNzgsImV4cCI6MTc0MDI1OTA3OH0.66lW5r3sRHk5JlhEPt2WJJvfYKBdfvdCJ9wApEkltgc